<?php

namespace Tests\Feature;

use App\Http\Resources\AuthenticatedUserResource as AuthenticatedUser;
use App\Repositories\AcademicTerm\AcademicTermRepositoryInterface;
use App\Repositories\User\UserRepositoryInterface;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AcademicTermControllerTest extends TestCase
{
    use RefreshDatabase;

    private AuthenticatedUser $auth;

    private AcademicTermRepositoryInterface $repository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = resolve(AcademicTermRepositoryInterface::class);
        $userRepository = resolve(UserRepositoryInterface::class);

        $userData = [
            'username' => 'Shan',
            'password' => 'testpass',
            'first_name' => 'Shan',
            'middle_name' => '',
            'last_name' => 'Padayhag'
        ];
        $userRepository->createUser($userData);
        $this->auth = $userRepository->authenticateUser($userData);
    }

    /**
     * @test
     * @dataProvider validAcademicTermDataProvider
     */
    public function it_can_create_academic_term_if_not_exist(array $academicTermData)
    {
        $response = $this->post('/api/v1/academic-term', $academicTermData, [
            'accept' => 'application/json',
            'authorization' => "Bearer {$this->auth->accessToken}"
        ]);

        $response->assertStatus(201);
        $response->assertJsonStructure([
            "id",
            "term",
            "created_at",
            "updated_at",
        ]);
    }

    /**
     * @test
     * @dataProvider validAcademicTermDataProvider
     */
    public function it_can_retrieve_academic_term_if_exist(array $academicTermData)
    {
        $this->repository->createAcademicTermIfNotExist($academicTermData);

        $response = $this->post('/api/v1/academic-term', $academicTermData, [
            'accept' => 'application/json',
            'authorization' => "Bearer {$this->auth->accessToken}"
        ]);

        $response->assertStatus(200);
        $response->assertJsonStructure([
            "id",
            "term",
            "created_at",
            "updated_at",
            'deleted_at',
        ]);
    }

    /**
     * @test
     * @dataProvider invalidAcademicTermDataProvider
     */
    public function it_should_respond_with_error_when_given_invalid_academic_year(array $academicTermData)
    {
        $response = $this->post('/api/v1/academic-term', $academicTermData, [
            'accept' => 'application/json',
            'authorization' => "Bearer {$this->auth->accessToken}"
        ]);

        $response->assertStatus(400);
    }

    /**
     * @test
     */
    public function it_can_set_current_academic_term()
    {
        $response = $this->get('/api/v1/set-current-academic-term/1', [
            'accept' => 'application/json',
            'authorization' => "Bearer {$this->auth->accessToken}"
        ]);

        $response->assertStatus(200);
    }

    /**
     * @test
     * @dataProvider validAcademicTermDataProvider
     */
    public function it_can_retrieve_all_academic_terms(array $academicTermData)
    {
        $this->repository->createAcademicTermIfNotExist($academicTermData);

        $response = $this->get('/api/v1/academic-term', [
            'accept' => 'application/json',
            'authorization' => "Bearer {$this->auth->accessToken}"
        ]);

        $response->assertStatus(200);
        $response->assertJsonStructure([
            'academic_terms' => [
                0 => [
                    'id',
                    'term',
                    'created_at',
                    'updated_at',
                    'deleted_at'
                ]
            ],
            'current_academic_term'
        ]);
    }
}
